// This file was autogenerated by ../bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../src/Board.js', ['hps.prime.Board'], []);
goog.addDependency('../../../src/Board_Factory.js', ['hps.prime.BoardFactory'], ['hps.prime.Board']);
goog.addDependency('../../../src/Board_UI.js', ['hps.prime.BoardUI'], ['goog.dom.classes', 'goog.events.EventTarget', 'goog.ui.Palette', 'goog.ui.Prompt', 'hps.prime.BoardFactory', 'hps.prime.GameOverEvent', 'hps.prime.NextTurnEvent']);
goog.addDependency('../../../src/Event_Type.js', ['hps.prime.EventType'], ['goog.events']);
goog.addDependency('../../../src/GameOver_Event.js', ['hps.prime.GameOverEvent'], ['goog.events.Event', 'hps.prime.EventType']);
goog.addDependency('../../../src/NextTurn_Event.js', ['hps.prime.NextTurnEvent'], ['goog.events.Event', 'hps.prime.EventType']);
goog.addDependency('../../../src/Player.js', ['hps.prime.Player'], []);
goog.addDependency('../../../src/PlayerList_UI.js', ['hps.prime.PlayerListUI'], ['goog.dom', 'goog.events', 'goog.events.EventType', 'goog.string', 'goog.ui.Button', 'goog.ui.FlatButtonRenderer', 'goog.ui.LabelInput', 'hps.prime.Player', 'hps.prime.PlayerList','goog.ui.CustomButton']);
goog.addDependency('../../../src/Player_List.js', ['hps.prime.PlayerList'], ['goog.structs']);
goog.addDependency('../../../src/main_UI.js', ['hps.prime.MainUI'], ['goog.Uri', 'goog.dom', 'goog.events', 'goog.events.EventType', 'goog.string', 'goog.string.StringBuffer', 'goog.ui.Button', 'goog.ui.FlatButtonRenderer', 'hps.prime.BoardUI', 'hps.prime.EventType', 'hps.prime.Player', 'hps.prime.PlayerList', 'hps.prime.PlayerListUI']);
goog.addDependency('../../../src/Boot.js', ['hps.prime.Boot'], ['hps.prime.MainUI','goog.dom']);


